# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

paginate:         1

baseurl:    
url:              https://datamacgyver.github.io/
# url:                https://localhost:4000/

author:
  name:           'Rob Mansfield'
  url:            https://twitter.com/dataMacgyver


# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/datamacgyver/datamacgyver.github.io
  site:           https://github.com/datamacgyver/

# Original Stuff
title: Data MacGyver
tagline: 'I have a paperclip and some freetext fields. Make me a general AI.'
author: Rob Mansfield
email: mansfieldbitter@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
    Data Science in Farming, by any means necessary.<br>
    Usually Python, R and a little ECL.
    <a href="https://twitter.com/dataMacgyver" target="_blank">@dataMacgyver</a>
  
# social links
twitter_username: datamacgyver
github_username: datamacgyver
linkedin_username: rpmansfield
linkedin_link: https://linkedin.com/in/rpmansfield
google_plus_username: 
facebook_username:    
dribbble_username:

show_excerpts: true # set to false to remove excerpts on the homepage
show_downloads: true
